#!/bin/bash
# Pre-tool safety hook: warn before editing sensitive files that have
# downstream consequences. Receives the tool call JSON on stdin.
#
# CUSTOMIZE: Add patterns for your project's sensitive file types.
# Exit 0 = allow; exit 2 = block with message.

# The event JSON arrives on stdin, but `python3 -` reads its program from
# stdin too (the heredoc below), so the event must be captured first and
# handed over in an env var. Reading sys.stdin inside the heredoc program
# finds EOF, the except branch exits 0, and the hook silently checks nothing.
HOOK_EVENT_JSON="$(cat)"
export HOOK_EVENT_JSON

python3 - <<'PYEOF'
import os, sys, json, re

try:
    data = json.loads(os.environ.get("HOOK_EVENT_JSON") or "{}")
    tool = data.get("tool_name", "")
    file_path = data.get("tool_input", {}).get("file_path", "")
except Exception:
    sys.exit(0)

# Only check Edit and Write operations
if tool not in ("Edit", "Write"):
    sys.exit(0)

if not file_path:
    sys.exit(0)

# ── Lock files — should not be hand-edited ──────────────────────────────────
# These are generated by package managers. Manual edits cause drift.
if re.search(r"(package-lock\.json|yarn\.lock|pnpm-lock\.yaml|Pipfile\.lock|poetry\.lock|uv\.lock|go\.sum|Cargo\.lock)$", file_path):
    print(f"BLOCKED: {file_path} is a lock file — regenerate it with the package manager instead of editing it.", file=sys.stderr)
    sys.exit(2)

# ── CI config — warn (don't block) ─────────────────────────────────────────
# GitHub Actions workflows and composite actions. `actionlint` catches most
# workflow mistakes locally, before a push spends a CI run discovering them.
if re.search(r"\.github/(workflows|actions)/", file_path):
    print(f"CI config modified: {file_path} — run actionlint and verify the workflow still works before pushing.")
    # Exit 0 = allow but show the message
    sys.exit(0)

# ── Environment files — warn about secrets ──────────────────────────────────
if re.search(r"\.env$|\.env\.local$|\.env\.production$", file_path):
    print(f"WARNING: {file_path} may contain secrets — do not commit this file.")
    sys.exit(0)

PYEOF
