#!/bin/bash
# Pre-tool safety hook: warn before editing sensitive files that have
# downstream consequences. Receives the tool call JSON on stdin.
#
# CUSTOMIZE: Add patterns for your project's sensitive file types.
# Exit 0 = allow; exit 2 = block with message.

python3 - <<'PYEOF'
import sys, json, re

try:
    data = json.load(sys.stdin)
    tool = data.get("tool_name", "")
    file_path = data.get("tool_input", {}).get("file_path", "")
except Exception:
    sys.exit(0)

# Only check Edit and Write operations
if tool not in ("Edit", "Write"):
    sys.exit(0)

if not file_path:
    sys.exit(0)

# ── Lock files — should not be hand-edited ──────────────────────────────────
# These are generated by package managers. Manual edits cause drift.
if re.search(r"(package-lock\.json|yarn\.lock|pnpm-lock\.yaml|Pipfile\.lock|poetry\.lock|uv\.lock|go\.sum|Cargo\.lock)$", file_path):
    print(f"WARNING: {file_path} is a lock file — it should be regenerated by the package manager, not edited directly.")
    sys.exit(2)

# ── Migration files — should not be modified after creation ─────────────────
# Editing an existing migration can corrupt production databases.
if re.search(r"migrations/\d", file_path):
    print(f"WARNING: {file_path} is a migration file — modifying existing migrations is dangerous. Create a new migration instead.")
    sys.exit(2)

# ── CI config — warn (don't block) ─────────────────────────────────────────
if re.search(r"\.gitlab-ci\.yml$|\.github/workflows/|ci/.*\.yml$", file_path):
    print(f"CI config modified: {file_path} — verify pipeline still works before pushing.")
    # Exit 0 = allow but show the message
    sys.exit(0)

# ── Environment files — warn about secrets ──────────────────────────────────
if re.search(r"\.env$|\.env\.local$|\.env\.production$", file_path):
    print(f"WARNING: {file_path} may contain secrets — do not commit this file.")
    sys.exit(0)

PYEOF
