#!/usr/bin/env bash
# scripts/tests/lib/app-fixture.sh — writes the application fixture that
# scripts/tests/app-fixture-gates.test.sh runs the application-aware gate
# (check-added-files-covered.mjs) against. Sourced, not executed.
#
# ## Why it is generated, not committed
#
# A toy app committed to the tree would sit beside the real application with
# nothing telling a reader it is gate-test scaffolding, and every code-reading
# tool (linters, coverage, the gate itself) would find it. So the fixture exists
# only inside a temp directory for the duration of a test run.
#
# ## What it contains
#
# A small Python-and-TypeScript-shaped app laid out the way the gate's built-in
# default layers expect (`backend/` + `.coveragerc`, `frontend/src/` +
# `vitest.config.ts`), with tests and type-only files the omit configs exclude,
# and coverage.py / vitest v8 Cobertura reports in the shapes those tools emit.
# Nothing in it is installed or executed; the gate parses it statically. When
# extending it, copy what the real tool produces — do not paraphrase it, or
# parser and fixture agree by construction.
#
# Coverage reports are written under reports/ (not at their real paths)
# because the runner builds git repos from backend/ and frontend/ and places
# the reports as untracked build output, as CI would.

# generate_fixture <root> — write the fixture tree under <root>.
generate_fixture() {
  local root="$1"
  mkdir -p "$root/backend/app/tests" \
    "$root/frontend/src/components" \
    "$root/frontend/src/types" \
    "$root/reports"

  cat > "$root/backend/.coveragerc" <<'FIXTURE_EOF'
[run]
source = .
branch = true
omit =
    */tests/*
    manage.py

[report]
skip_empty = false
FIXTURE_EOF
  : > "$root/backend/app/__init__.py"

  cat > "$root/backend/app/parser.py" <<'FIXTURE_EOF'
"""Toy broker-export parser for the gate fixture. Never imported or executed."""

import csv
from decimal import Decimal


def parse_trades(handle):
    """Yield (symbol, quantity, price) rows from a CSV export."""
    for row in csv.DictReader(handle):
        yield row["Symbol"], Decimal(row["Quantity"]), Decimal(row["Price"])
FIXTURE_EOF

  cat > "$root/backend/app/report.py" <<'FIXTURE_EOF'
"""Toy report builder for the gate fixture. Never imported or executed."""

from .parser import parse_trades


def total_value(handle):
    return sum(qty * price for _, qty, price in parse_trades(handle))
FIXTURE_EOF
  : > "$root/backend/app/tests/__init__.py"

  cat > "$root/backend/app/tests/test_report.py" <<'FIXTURE_EOF'
import io

from app.report import total_value


def test_total_value():
    data = io.StringIO("Symbol,Quantity,Price\nABC,2,10.5\n")
    assert total_value(data) == 21
FIXTURE_EOF

  cat > "$root/frontend/src/components/Summary.test.tsx" <<'FIXTURE_EOF'
import { render, screen } from "@testing-library/react";
import { expect, it } from "vitest";

import { Summary } from "./Summary";

it("renders the total", () => {
  render(<Summary report={{ total: "21.00", rows: 1 }} />);
  expect(screen.getByText(/21.00/)).toBeTruthy();
});
FIXTURE_EOF

  cat > "$root/frontend/src/components/Summary.tsx" <<'FIXTURE_EOF'
import type { SummaryProps } from "../types";

export function Summary({ report }: SummaryProps) {
  return (
    <p>
      {report.rows} rows, total {report.total}
    </p>
  );
}
FIXTURE_EOF

  cat > "$root/frontend/src/types/index.ts" <<'FIXTURE_EOF'
/** Type-only module: no runtime code, so vitest's coverage.exclude omits it. */

export interface Report {
  total: string;
  rows: number;
}

export interface SummaryProps {
  report: Report;
}
FIXTURE_EOF

  cat > "$root/frontend/vitest.config.ts" <<'FIXTURE_EOF'
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "jsdom",
    coverage: {
      provider: "v8",
      reporter: ["text", "cobertura"],
      include: ["src/**/*.{ts,tsx}"],
      exclude: ["src/**/*.test.*", "src/types/**", "src/vite-env.d.ts"],
    },
  },
});
FIXTURE_EOF

  cat > "$root/reports/backend-coverage.xml" <<'FIXTURE_EOF'
<?xml version="1.0" ?>
<coverage version="7.6.1" timestamp="1790000000000" lines-valid="9" lines-covered="9" line-rate="1" branches-covered="0" branches-valid="0" branch-rate="0" complexity="0">
	<!-- Generated by coverage.py: https://coverage.readthedocs.io/en/7.6.1 -->
	<sources>
		<source>/builds/acme/app/backend</source>
	</sources>
	<packages>
		<package name="app" line-rate="1" branch-rate="0" complexity="0">
			<classes>
				<class name="__init__.py" filename="app/__init__.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines/>
				</class>
				<class name="parser.py" filename="app/parser.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines>
						<line number="3" hits="1"/>
						<line number="7" hits="1"/>
					</lines>
				</class>
				<class name="report.py" filename="app/report.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines>
						<line number="3" hits="1"/>
						<line number="7" hits="1"/>
					</lines>
				</class>
			</classes>
		</package>
	</packages>
</coverage>
FIXTURE_EOF

  cat > "$root/reports/frontend-cobertura.xml" <<'FIXTURE_EOF'
<?xml version="1.0" ?>
<!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd">
<coverage lines-valid="2" lines-covered="2" line-rate="1" branches-valid="0" branches-covered="0" branch-rate="1" timestamp="1790000000000" complexity="0" version="0.1">
  <sources>
    <source>/builds/acme/app/frontend</source>
  </sources>
  <packages>
    <package name="src.components" line-rate="1" branch-rate="1">
      <classes>
        <class name="Summary.tsx" filename="src/components/Summary.tsx" line-rate="1" branch-rate="1">
          <methods>
            <method name="Summary" hits="1" signature="()V">
              <lines>
                <line number="3" hits="1"/>
              </lines>
            </method>
          </methods>
          <lines>
            <line number="3" hits="1"/>
          </lines>
        </class>
      </classes>
    </package>
  </packages>
</coverage>
FIXTURE_EOF
}
